apiVersion: "v1"
kind: Service
metadata:
 name: nginx-lb-k8s-service-paritoshlouhan
 labels: 
  app: dotnet-app-lb
spec:
 type: LoadBalancer
 ports:
  - name: http
    port: 80
    targetPort: 5000
  - name: https
    port: 443
    targetPort: 5001
 selector:
  app: dotnet-app
  
