apiVersion: apps/v1
kind: Deployment
metadata:
 name: nginx-k8s-deployment
spec:
 strategy:
  type: Recreate
 replicas: 4
 selector:
   matchLabels:
    app: nginx-k8s-deployment-app
 template:
   metadata:
    name: nginx-k8s-pod
    labels:
     app: nginx-k8s-deployment-app
   spec:
     containers:
     - name: nginx-k8s-container
       image: paritoshlouhan/test2:jhooq-docker-demo
