apiVersion: apps/v1
kind: Deployment
metadata:
 name: nginx-k8s-deployment-paritoshlouhan
 labels: 
  app: dotnet-app
spec:
 strategy:
  type: Recreate
 replicas: 4
 selector:
   matchLabels:
    app: dotnet-app
 template:
   metadata:
    labels:
     app: dotnet-app
   spec:
     containers:
     - name: dotnet-app
       image: paritoshlouhan/test2:jhooq-docker-demo
       imagePullPolicy: Always
       ports:
        - name: http
          containerPort: 80
        - name: https
          containerPort: 443
