apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: k8s-replicaset
  labels:
    app: k8s-replicaset-app
spec:
  template:
    metadata:
      name: k8s-pod
      labels:
        app: k8s-app
        type: front-end
    spec:
      containers:
        - name: nginx-container
          image: paritoshlouhan/i-paritoshlouhan-master
  replicas: 4
  selector:
    matchLabels:
      app: k8s-app
      type: front-end